[workspace]
name = "sqlite-fire"
version = "0.1.0"
channels = ["https://conda.modular.com/max-nightly", "conda-forge"]
platforms = ["osx-arm64", "linux-64"]

[tasks]
smoke = "mojo run examples/basic.mojo"
test = "mojo test tests"

[dependencies]
mojo = ">=0.25.7"
sqlite = ">=3.51"
